### ISSUE TITLE
Feedback: 14th January 2016 XKE 

### ISSUE THREAD

**Issue by shekhargulati** [shekhargulati/git-the-missing-tutorial#4]
Please write your feedback in comments.  Write two points you like about XKE and two improvement points. If you didn't liked the session, then only write the improvement points.

This will help me prepare better for next XKE.

**Comment by jasleen123** [comment]
1. I liked the way of delivering and sharing knowledge.
2. It was a great experience overall.

**Comment by guptayuvraj** [comment]
Hi Shekhar 

It was a very informative XKE especially for newbies like me who have zero experience of using GIT. I was always afraid of the word GIT and yet this XKE changed my perspective towards the same.

Positive Things:-
1. Informative XKE with proper Hands-on covering each aspect.
2. Very helpful instructor solving problem's of people whenever occurred.

Improvements:-
1. Some concepts required detailed understanding which was  not provided. (I know being a basic GIT XKE but still in some commands/concepts, clarity was missing on usage of the command.)
2. In few commands/concepts the flow of delivery was little fast as compared to the overall flow.

These views are solely mine which can be right or wrong. 
:+1: for XKE & @shekhargulati

**Comment by Ankitkapoor4986** [comment]
It was a nice one.Learnt the things which I missed in spite of working for few months with GIT

**Comment by sheetalsingh** [comment]
Nice session learnt a lot 

Improvement:
1. Covered lot of thing in 3 Hrs, I think we can go a bit slow and can organize more session on GIT
2. More session on merge conflicts, rebase etc to get comfortable

**Comment by jasjuneja** [comment]
Nice session, lot of doubts are clear now ,definitely need an advanced version.

Thanks

**Comment by jasjuneja** [comment]
Nice session, lot of doubts are clear now ,definitely need an advanced version.

Thanks

**Comment by madhavij** [comment]
Thank you for delivering a great session.  
1.The session had relevant content with respect to our day to day work, hence very helpful.
2. A lot of personal doubts got cleared.

The pace could have been kept comparably slower at tricky topics. 

Now that the basics have been covered, looking forward to attend a session on an intermediate /advanced Git session.

**Comment by ShankarGargXebia** [comment]
Well Planned Session. StepWise learning. Awesome Learning.
